# Site settings
title: Tyskland
client:
  name: Alt fra julekos til spa og mat i Tyskland
  link: "#client-name"
core-se-link: https://no.secretescapes.com/aktuelle-tilbud
description: >
  Kom i julestemning, slapp av på spa eller bare nyt god mat.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/tyskland" # the subpath of your site, e.g. /blog/
img:     "/tyskland/_assets/img"
css:     "/tyskland/_assets/css"
js:      "/tyskland/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
