# Site settings
title: Tyskland
client:
  name: Alt fra julekos til spa og mat i Tyskland
  link: "http://bit.ly/2yzG1QY"
core-se-link: https://no.secretescapes.com/aktuelle-tilbud
description: >
  Har du lyst til å reise på en storbytur til Tyskland? I tillegg til spennende opplevelser og severdigheter i Berlin, kan du også utforske Münchens vakre arkitektur, Hamburgs kunst og kultur, finansbyen Frankfurt eller Düsseldorf som er full av nydelige parker.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/tyskland" # the subpath of your site, e.g. /blog/
img:     "/tyskland/_assets/img"
css:     "/tyskland/_assets/css"
js:      "/tyskland/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
